services:
  app:
    build: .
    image: studio-asset
    container_name: studio-asset
    restart: unless-stopped
    ports:
      - '127.0.0.1:3000:3000'
    logging: # apply better controls to Docker overlay folder
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
    environment:
      - PROJECT_ID=${PROJECT_ID} # change to match your own environment
      - PROJECT_NAME=${PROJECT_NAME} # change to match your own environment
      - PROJECT_MNEMONIC=${PROJECT_MNEMONIC} # change to match your own environment
