services:
  cdn:
    build: .
    image: cdn
    container_name: cdn
    restart: unless-stopped
    ports:
      - '127.0.0.1:3000:80'
    logging: # apply better controls to Docker overlay folder
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
