# Initialize Nginx (alpine edition)
FROM nginx:alpine

# Copy all MAIN source files
COPY ./src /usr/share/nginx/html

# Copy all ASSET source files
COPY ./assets /usr/share/nginx/html/assets

# Copy all SNIPPET source files
COPY ./snippets /usr/share/nginx/html/snippets
