services:
  app:
    build: .
    image: docs
    container_name: docs
    restart: unless-stopped
    ports:
      - '127.0.0.1:4000:80'
    logging: # apply better controls to Docker overlay folder
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
