version: '3.7'

services:
  app:
    build: .
    image: studio-nft
    container_name: studio-nft
    restart: always
    ports:
      - '127.0.0.1:5400:3000'   # use with proxy server (eg. Nginx)
      # - '0.0.0.0:80:3000'     # use without proxy server
    logging: # apply better controls to Docker overlay folder
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
    environment:
      - PROJECT_ID=${PROJECT_ID} # change to match your own environment
      - PROJECT_NAME=${PROJECT_NAME} # change to match your own environment
      - PROJECT_MNEMONIC=${PROJECT_MNEMONIC} # change to match your own environment
