services:
  app:
    build: .
    image: studio-lounge
    container_name: studio-lounge
    restart: unless-stopped
    ports:
      - '127.0.0.1:3000:3000'   # use with proxy server (eg. Nginx)
      # - '0.0.0.0:80:3000'     # use without proxy server
    logging: # apply better controls to Docker overlay folder
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
    environment:
      - MNEMONIC=${MNEMONIC}
